### ISSUE TITLE
[Bug]:修复bug

### ISSUE THREAD

**Issue by teaping** [phpjavac/composition#81]
### bug描述

useHover事情触发失败 
useAwaitDom模块导入失败 
usePermission模块导入失败 
useClipboard模块导入失败 
useTitle模块导入失败 

### 版本号

0.0.1 (Default)

### 在哪些浏览器上看到这个问题？

Chrome

### Contact Details

small_xia@126.com

**Comment by phpjavac** [comment]
useHover  基本用法 显示错误 error:```isHovering:[object` Object]```
